// Generated by CoffeeScript 1.8.0
(function() {
  var controller, devices, ds4, hid, hidDevice, isBluetoothHID, isDS4HID, isUSBHID, offset, parseDS4HIDData, _;

  _ = require('./node_modules/ds4/node_modules/lodash');

  hid = require('./node_modules/ds4/node_modules/node-hid');

  ds4 = require('./node_modules/ds4');

  parseDS4HIDData = ds4.parseDS4HIDData;

  devices = hid.devices();

  controller = _(devices).filter(isDS4HID).first();

  if (!controller) {
    throw new Error('Could not find desired controller.');
  }

  hidDevice = new hid.HID(controller.path);

  offset = 0;

  isDS4HID = function(descriptor) {
    return descriptor.vendorId === 1356 && descriptor.productId === 1476;
  };

  isBluetoothHID = function(descriptor) {
    return descriptor.path.match(/^Bluetooth/);
  };

  isUSBHID = function(descriptor) {
    return descriptor.path.match(/^USB/);
  };

  if (isBluetoothHID(controller)) {
    offset = 2;
    hidDevice.getFeatureReport(0x04, 66);
  }

  hidDevice.on('data', function(buf) {
    return console.log(parseDS4HIDData(buf.slice(offset)));
  });

}).call(this);

//# sourceMappingURL=shockmouse.js.map
